### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by tron1991** [pinguo-zhangzhi/ZZGallerySliderView#1]
Hi Pinguo-zhangzhi,

What is the licensing for ZZGallerySliderView if any?

-Tron1991

**Comment by pinguo-zhangzhi** [comment]
Thank you for your comment. I am sorry I am not sure whether I got licensing or not since I can not remember the option I selected. Anyway, you can use it since I got the MIT. Let me know if you have any other query.

**Comment by tron1991** [comment]
Thanks for responding. MIT License, it is
